### ISSUE TITLE
Fix vim's lcd issue

### ISSUE THREAD

**Issue by zhimsel** [zhimsel/dotfiles#13]
https://github.com/kopischke/vim-stay/issues/10

**Comment by blueyed** [comment]
Any progress on that? ;)

**Comment by zhimsel** [comment]
Not really :/

**Comment by blueyed** [comment]
I've switched on the workaround from https://github.com/kopischke/vim-stay/issues/10#issuecomment-83691770 again, with handling of Neovim's `:tcd`.
